### ISSUE TITLE
Error During Installation - there is no package called ‘quadprog’ leads to    could not find function "setar.sim"

### ISSUE THREAD

**Issue by Firiyuu** [MatthieuStigler/tsDyn#10]
Hello, a little bit of help here, during installation I get this error:
```

Error: package or namespace load failed for ‘tsDyn’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘quadprog’
```

With that I cant use **setar.sim** function
```
Error in setar.sim(B = TvarMat, lag = 2, type = "simul", nthresh = 1,  : 
  could not find function "setar.sim"
```

**Comment by Firiyuu** [comment]
What I tried so far:

-Installing from github
-Having the dependency parameter set to TRUE

**Comment by MatthieuStigler** [comment]
I am not sure why it is complaining about package `quadrpog`, as it is not a direct dependency of tsDyn. But try installing this one first, then try tsDyn again!

**Comment by Firiyuu** [comment]
Hello sir, the thing is when I try to install quadprog

```
install.packages('quadprog')
Installing package into ‘C:/Users/storm/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘quadprog’ is not available (for R version 3.5.3)
```

This error surfaces and when I try to install tsDyn again its still looking for quadprog.

**Comment by MatthieuStigler** [comment]
I see. This is bad news: it turns out the latest version of quadprog requires R 3.6...

At that point, I see two solutions:

- You upgrade your R to 3.6
- You download manually a previous version of quadprog, try from https://cran.r-project.org/src/contrib/Archive/quadprog/

You should find many resources online for each solution.

**Comment by Firiyuu** [comment]
Thank you, I will try it. Actually my R was at 3.6 I thought that the new version might be so updated. So I stepped down to 5.3, but nothing happened, but thanks for the prev version of quadprog :)

**Comment by MatthieuStigler** [comment]
ok good, so I will close the issue!
