### ISSUE TITLE
TVECM.SeoTest

### ISSUE THREAD

**Issue by Farhanggc** [MatthieuStigler/tsDyn#19]
Sir I am using tsDyn package but the function TVECM.SeoTest for testing no Cointegration against threshold Cointegration is not working.

**Comment by MatthieuStigler** [comment]
Can you please provide a reproducible example? see https://stackoverflow.com/questions/5963269/how-to-make-a-great-r-reproducible-example

**Comment by MatthieuStigler** [comment]
Closed for lack of info/follow-up. Feel free to re-open if you have a reprex!
