### ISSUE TITLE
Suggestions for coefB() help page

### ISSUE THREAD

**Issue by philturk** [MatthieuStigler/tsDyn#21]
Hi:

Thank you for taking the time and effort to put together the really useful `tsDyn` package. I have a few suggestions to tighten up the `coefB()` help page with respect to your discussion on Phillips triangular representation:

1. You currently say have A_{norm} = B'c. It is actually A_{norm} = AB'c.
2. Please define p (e.g., as in 0_{p-r,r}).
3. Please list Johansen (1995) in a References section.

The aforementioned will not be obvious to those who do not spend time fitting VECMs.

Best,

-- Phil

**Comment by MatthieuStigler** [comment]
Hi @philturk 

Thanks for the report! It took a long time, but corrected in the next version coming soon.
