### ISSUE TITLE
lag length test

### ISSUE THREAD

**Issue by Paviaym** [MatthieuStigler/tsDyn#30]
I could not see a function about the determination of lag length for unit root tests, for instance for BBC or kapshintest. Can you please recommend a way to decide on the lag length in the execution of these tests? I was happy to see lags.select but later noticed that it is for cointegrated vectors.

**Comment by MatthieuStigler** [comment]
Hi Brian

> Disclaimer: it has been a while I haven't used this model, and I am not up to date with the literature

I am not aware of specific criterion for lag length selection in the threshold unit root context. I would rely on tools for linear unit root tests. I think a major contribution was Ng and Perron (2001) modified AIC (not available in `tsDyn`), but there is surely something new in the meanwhile. See also this [Stack post](https://stats.stackexchange.com/questions/147956/lag-selection-for-augmented-dickey-fuller-test)

**Comment by Paviaym** [comment]
Dear Matthieu,

Thank you for your response. I will check the post and paper you shared.

Best regards

Paviaym
