### ISSUE TITLE
install tsdyn

### ISSUE THREAD

**Issue by mariajesus1980** [MatthieuStigler/tsDyn#33]
Dear Matthieu,

I am trying to install your packages from different ways, but I cant. Below what I tried and the reported error:
1. > library(tsDyn)
Error: package or namespace load failed for ‘tsDyn’ in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]):
 there is no package called ‘tmvnsim’

2. I download your master code from here, and I tried to install locally:
> utils:::menuInstallLocal()
Error in read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) : 
  no se puede abrir la conexión
Además: Warning message:
In read.dcf(file.path(pkgname, "DESCRIPTION"), c("Package", "Type")) :
  cannot open compressed file 'tsDyn-master/DESCRIPTION', probable reason 'No such file or directory'

as I am trying to work with your code, can you please guide how to fix the error and to load the package into the library?

many thanks in advanced

best wishes,
maria jesus

**Comment by MatthieuStigler** [comment]
Hi

Just try:


```
library(devtools)
install_github("MatthieuStigler/tsDyn/tsDyn")
```

**Comment by mariajesus1980** [comment]
Hi again,

I tried to do it:
> install_github("MatthieuStigler/tsDyn/tsDyn") 
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 4.0 from https://cran.r-project.org/bin/windows/Rtools/.
Downloading GitHub repo MatthieuStigler/tsDyn@HEAD
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 4.0 from https://cran.r-project.org/bin/windows/Rtools/.
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 4.0 from https://cran.r-project.org/bin/windows/Rtools/.
Error: Failed to install 'tsDyn' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.
Además: Warning messages:
1: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers
2: In untar2(tarfile, files, list, exdir) :
  skipping pax global extended headers


and I tried to install Rtools again from local and like this:

install_github("r-windows/rtools-packages.git") 
> install_github("r-windows/rtools-packages") 
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 4.0 from https://cran.r-project.org/bin/windows/Rtools/.
Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  Not Found

  Did you spell the repo owner (`r-windows`) and repo name (`rtools-packages`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.


I am using R 4.0.5

can you help please?

many thanks.

**Comment by MatthieuStigler** [comment]
As indicated: *WARNING: Rtools is required to build R packages, but is not currently installed*
you need to install Rtools on your machine

**Comment by mariajesus1980** [comment]
i tried to do it. but didnt work.
how could i install it please?

**Comment by mariajesus1980** [comment]
Hi
I fix the issue by doing this: 
https://cran.r-project.org/bin/windows/Rtools/index.html

and later your lines to install your library in R 4.0.5

many thanks

**Comment by MatthieuStigler** [comment]
great.
