### ISSUE TITLE
TVAR exogeneous variable

### ISSUE THREAD

**Issue by mundrasruti** [MatthieuStigler/tsDyn#36]
Hello

How can we add exogeneous variable in TVAR?

**Comment by ninowski** [comment]
I too am interested, thank you.

**Comment by MatthieuStigler** [comment]
I believe this is clearly stated in the documentation, isn't? See:

- `thVar`: Optional. External transition variable.

I am going to close this issue, if you still have doubts please re-open it by providing a reprex: https://reprex.tidyverse.org/
