### ISSUE TITLE
Wrong number of lags for startVal in VECM.sim

### ISSUE THREAD

**Issue by bixiou** [MatthieuStigler/tsDyn#4]
Function VECM.sim requires a matrix of starting values of dimension nB*p instead of nB*(p+1), where p is the number of lags. In lines 227-230 of [TVECM.sim.R](https://github.com/MatthieuStigler/tsDyn/blob/master/tsDyn/R/TVECM.sim.R), 'p' should be replaced by 'p+1'. Also, there is a confusion between rows and columns. Here are the corrected lines.

```
    if(all(dim(as.matrix(starting))==c(p+1,nB)))
      y[seq_len(p+1),]<-starting
    else
	stop("Bad specification of starting values. Should have nrow = lag+1 and ncol = number of variables")
```

**Comment by MatthieuStigler** [comment]
I see, I made a few changes anyway, could you please create a reproducible example? Thanks!

**Comment by bixiou** [comment]
Sorry it's been a while I totally forgot this issue and where I encountered it.

**Comment by MatthieuStigler** [comment]
no problem, my fault for not getting back earlier. Anyway, there;s anew version coming soon with another code. I'll close and if you encounter the problem again, please let me know!
