### ISSUE TITLE
Define shock variable in GIRF

### ISSUE THREAD

**Issue by ZhepengHuCAU** [MatthieuStigler/tsDyn#41]
Hi Matthieu:

Thanks for maitaining this package. I used the GIRF years before from this package and now find this new version has some changes. I have trouble finding the way to define the shock varaible in the GIRF. Before, we can use thvar to define which is the shock variable. If would be very helpful if you can clealfy this. 

Thank you.

**Comment by MatthieuStigler** [comment]
Hi

Can you please produce minimal self-reproducible code for your issue?
