### ISSUE TITLE
rdocumentation inconstistency for VECM

### ISSUE THREAD

**Issue by Nesta-gitU** [MatthieuStigler/tsDyn#50]
VECM doc: LRinclude
Type of deterministic regressors to include in the long-term relationship. Can also be a matrix with exogeneous regressors (2OLS only).

lineVar doc: LRinclude
Type of deterministic regressors to include in the long-term relationship. Can also be a matrix with exogeneous regressors.

Should both be like in the lineVar documentation

**Comment by MatthieuStigler** [comment]
Good point, thanks for raising this!
