### ISSUE TITLE
`ci` argument in `predict.nlar` is handled unconventionally

### ISSUE THREAD

**Issue by ha0ye** [MatthieuStigler/tsDyn#8]
My expectation when asking for a CI = 0.95 is that the CI will span 95%, meaning the quantiles are 2.5% and 97.5%.

Instead it appears that the CI = 0.95 gives a 90% CI, by getting quantiles at 5% and 95%. 
```
# line 130 of `predict.R`
... prob=sort(c(1-ci, ci)) ...
```

I think this is a pretty simple fix. Let me know if you'd like a PR and accompanying tests.

**Comment by MatthieuStigler** [comment]
Well spotted, thanks! I fixed it in the Dev version:
https://github.com/MatthieuStigler/tsDyn/tree/Dev94

Thanks
