### ISSUE TITLE
Heteroskedasticity

### ISSUE THREAD

**Issue by Tsumbu** [MatthieuStigler/tsDyn#9]
Dear Mr Matthieu Stigler,
I am using the SETAR and the LSTAR model to model and forecast return. I want to ask if there is a way to account for heteroskedasticity in the tsDyn package so that I can have correct inference.

I am particularly interested in accounting for heteroskedasticity in the setarTest(), lstar() and in the setar() function.

**Comment by MatthieuStigler** [comment]
Hi

There is no methods for now to allow HC covariance in tsDyn. For SETAR models, you can just extract the model-matrix from the SETAR output and re-run it using lm() and sandwhich. For LSTAR, this is more tricky, I am not sure how to derive the relevant expressions.

**Comment by MatthieuStigler** [comment]
Closing this issue as inactive for a while.
